# Generated by Django 4.1.6 on 2023-05-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_alter_jihaz_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='type',
        ),
    ]
