# Generated by Django 4.1.6 on 2023-06-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jihaz',
            name='material',
            field=models.CharField(max_length=100),
        ),
    ]
