# Generated by Django 4.2 on 2023-07-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_alter_jihaz_material'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Klient',
        ),
    ]
